name: Test Node.js App

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install jest
      run: npm install --save-dev jest

    - name: Install lint
      run: npm install eslint eslint-plugin-complexity --save-dev

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm run test:coverage